#pragma once
#define SERIAL_BUAD 19200

#define SERIAL_DEBUGGING false

#define ARC_START_RETRY_LIMIT 5
#define ARC_START_TIMEOUT 1500
#define ARC_START_intERLOCK_TIMEOUT 3000

#define DIGITAL_IN_PIN_AC_OK 7
#define DIGITAL_IN_PIN_OVER_TEMP 6
#define DIGITAL_IN_PIN_GAS_OK 5
#define DIGITAL_IN_PIN_DC_OK 4

#define DIGITAL_OUT_PIN_TORCH_FIRE 8

#define ANALOG_IN_PIN_PILOT_ARC_VOLTAGE A0
#define ANALOG_IN_PIN_MAIN_ARC_VOLTAGE A1

